# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('socket-bridge-example', ['socket-bridge', 'wifi', 'mobility'])
    obj.source = 'socket-bridge-example.cc'
    #obj = bld.create_ns3_program('socket-bridge-ann-example', ['socket-bridge', 'wifi', 'mobility'])
    #obj.source = 'socket-bridge-ann-example.cc'

